# Generated by Django 3.2.13 on 2022-04-29 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_satecity'),
    ]

    operations = [
        migrations.AddField(
            model_name='satecity',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
